# Generated by Django 4.2.7 on 2023-11-17 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_classroomteacher_classroom_teachers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClassRoomTeacher',
        ),
    ]
