# Generated by Django 4.2.7 on 2023-11-18 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_delete_classroomteacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('max_score', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UnionExamCourseScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('absent', models.BooleanField(default=False)),
                ('cheat', models.BooleanField(default=False)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.course')),
                ('exam_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.unionexam')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.student')),
            ],
        ),
        migrations.DeleteModel(
            name='UnionExamScore',
        ),
    ]
