# Generated by Django 4.2.7 on 2023-11-19 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_course_unionexamcoursescore_delete_unionexamscore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
